version: '3.8'

services:
  cursopythonia:
    image: nginx:alpine
    container_name: cursopythonia_web
    ports:
      - "8085:80"
    volumes:
      - ./:/usr/share/nginx/html:ro
    restart: unless-stopped
